namespace Snipper.Tests;

using FluentAssertions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using Snipper.Analysis;
using Xunit;

public sealed class SolutionReferenceIndexShould
{
    [Fact]
    public async Task Include_Generated_And_External_Documents_As_Usage_Evidence_For_GetUsedAssemblies()
    {
        // Arrange: a library project plus a consumer that touches the library ONLY
        // from a generated file (obj\...) and a file linked from outside the
        // project directory. Both are usage evidence and must count.
        using var workspace = new AdhocWorkspace();
        var corlib = MetadataReference.CreateFromFile(typeof(object).Assembly.Location);

        var libId = ProjectId.CreateNewId("Lib");
        var consumerId = ProjectId.CreateNewId("Consumer");

        var solution = workspace.CurrentSolution
            .AddProject(ProjectInfo.Create(libId, VersionStamp.Create(), "Lib", "Lib", LanguageNames.CSharp,
                filePath: @"C:\repo\Lib\Lib.csproj"))
            .AddDocument(DocumentId.CreateNewId(libId), "LibType.cs", SourceText.From("namespace Lib; public sealed class LibType { }"),
                filePath: @"C:\repo\Lib\LibType.cs")
            .AddProject(ProjectInfo.Create(consumerId, VersionStamp.Create(), "Consumer", "Consumer", LanguageNames.CSharp,
                filePath: @"C:\repo\Consumer\Consumer.csproj"))
            .AddMetadataReference(consumerId, corlib)
            .AddProjectReference(consumerId, new ProjectReference(libId))
            .AddDocument(DocumentId.CreateNewId(consumerId), "Gen.cs", SourceText.From(
                "// <auto-generated/>\nnamespace Consumer; public sealed class GenUsage { public static Lib.LibType? Create() => null; }"),
                filePath: @"C:\repo\Consumer\obj\Gen.cs")
            .AddDocument(DocumentId.CreateNewId(consumerId), "External.cs", SourceText.From(
                "namespace Consumer; public sealed class ExternalUsage { public static Lib.LibType? Create() => null; }"),
                filePath: @"C:\elsewhere\External.cs");

        var consumer = solution.GetProject(consumerId)!;

        // Act
        var usedAssemblies = SolutionReferenceIndex.Get(solution).GetUsedAssemblies(consumer);

        // Assert: the library assembly is used even though no non-skipped document references it.
        usedAssemblies.Should().Contain(a => a.Name == "Lib");
    }

    [Fact]
    public async Task Mark_Implementations_Alive_When_Any_Fellow_Implementation_Is_Called_For_IsReferenced()
    {
        // Arrange: the FindReferencesAsync contract family — a call binding one
        // implementation of a contract keeps every implementation alive (probe-
        // proven 2026-09-18: SymbolEqualityComparer.Default.Equals kept a fellow
        // IEqualityComparer implementation referenced in the dogfood run).
        using var workspace = new AdhocWorkspace();
        var corlib = MetadataReference.CreateFromFile(typeof(object).Assembly.Location);

        var projectId = ProjectId.CreateNewId("App");
        var solution = workspace.CurrentSolution
            .AddProject(ProjectInfo.Create(projectId, VersionStamp.Create(), "App", "App", LanguageNames.CSharp,
                filePath: @"C:\repo\App\App.csproj"))
            .AddMetadataReference(projectId, corlib)
            .AddDocument(DocumentId.CreateNewId(projectId), "Contracts.cs", SourceText.From("""
                namespace App;
                public interface IContract { int RuleIds { get; } }
                public sealed class FirstImpl : IContract { public int RuleIds => 1; }
                public sealed class SecondImpl : IContract { public int RuleIds => 2; }
                public static class Caller { public static int Use(IContract contract) => contract.RuleIds; }
                """),
                filePath: @"C:\repo\App\Contracts.cs");

        var document = solution.GetProject(projectId)!.Documents.Single();
        var model = await document.GetSemanticModelAsync();
        var root = await document.GetSyntaxRootAsync();
        var secondImpl = (INamedTypeSymbol)model!.GetDeclaredSymbol(
            root!.DescendantNodes().First(n => n is Microsoft.CodeAnalysis.CSharp.Syntax.ClassDeclarationSyntax c && c.Identifier.Text == "SecondImpl"))!;
        var secondImplRuleIds = secondImpl.GetMembers("RuleIds").Single();

        // Act + assert: only FirstImpl's RuleIds is ever bound (via the contract),
        // yet the fellow implementation counts as referenced too.
        SolutionReferenceIndex.Get(solution).IsReferenced(secondImplRuleIds).Should().BeTrue();
    }
}
