namespace Snipper.Tests;

using FluentAssertions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using Snipper.Analysis;
using Xunit;

public sealed class SolutionReferenceIndexShould
{
    [Fact]
    public async Task Include_Generated_And_External_Documents_As_Usage_Evidence_For_GetUsedAssemblies()
    {
        // Arrange: a library project plus a consumer that touches the library ONLY
        // from a generated file (obj\...) and a file linked from outside the
        // project directory. Both are usage evidence and must count.
        using var workspace = new AdhocWorkspace();
        var corlib = MetadataReference.CreateFromFile(typeof(object).Assembly.Location);

        var libId = ProjectId.CreateNewId("Lib");
        var consumerId = ProjectId.CreateNewId("Consumer");

        var solution = workspace.CurrentSolution
            .AddProject(ProjectInfo.Create(libId, VersionStamp.Create(), "Lib", "Lib", LanguageNames.CSharp,
                filePath: @"C:\repo\Lib\Lib.csproj"))
            .AddDocument(DocumentId.CreateNewId(libId), "LibType.cs", SourceText.From("namespace Lib; public sealed class LibType { }"),
                filePath: @"C:\repo\Lib\LibType.cs")
            .AddProject(ProjectInfo.Create(consumerId, VersionStamp.Create(), "Consumer", "Consumer", LanguageNames.CSharp,
                filePath: @"C:\repo\Consumer\Consumer.csproj"))
            .AddMetadataReference(consumerId, corlib)
            .AddProjectReference(consumerId, new ProjectReference(libId))
            .AddDocument(DocumentId.CreateNewId(consumerId), "Gen.cs", SourceText.From(
                "// <auto-generated/>\nnamespace Consumer; public sealed class GenUsage { public static Lib.LibType? Create() => null; }"),
                filePath: @"C:\repo\Consumer\obj\Gen.cs")
            .AddDocument(DocumentId.CreateNewId(consumerId), "External.cs", SourceText.From(
                "namespace Consumer; public sealed class ExternalUsage { public static Lib.LibType? Create() => null; }"),
                filePath: @"C:\elsewhere\External.cs");

        var consumer = solution.GetProject(consumerId)!;

        // Act
        var usedAssemblies = SolutionReferenceIndex.Get(solution).GetUsedAssemblies(consumer);

        // Assert: the library assembly is used even though no non-skipped document references it.
        usedAssemblies.Should().Contain(a => a.Name == "Lib");
    }

    [Fact]
    public async Task Mark_Implementations_Alive_When_Any_Fellow_Implementation_Is_Called_For_IsReferenced()
    {
        // Arrange: the FindReferencesAsync contract family — a call binding one
        // implementation of a contract keeps every implementation alive (probe-
        // proven 2026-09-18: SymbolEqualityComparer.Default.Equals kept a fellow
        // IEqualityComparer implementation referenced in the dogfood run).
        using var workspace = new AdhocWorkspace();
        var corlib = MetadataReference.CreateFromFile(typeof(object).Assembly.Location);

        var projectId = ProjectId.CreateNewId("App");
        var solution = workspace.CurrentSolution
            .AddProject(ProjectInfo.Create(projectId, VersionStamp.Create(), "App", "App", LanguageNames.CSharp,
                filePath: @"C:\repo\App\App.csproj"))
            .AddMetadataReference(projectId, corlib)
            .AddDocument(DocumentId.CreateNewId(projectId), "Contracts.cs", SourceText.From("""
                namespace App;
                public interface IContract { int RuleIds { get; } }
                public sealed class FirstImpl : IContract { public int RuleIds => 1; }
                public sealed class SecondImpl : IContract { public int RuleIds => 2; }
                public static class Caller { public static int Use(IContract contract) => contract.RuleIds; }
                """),
                filePath: @"C:\repo\App\Contracts.cs");

        var document = solution.GetProject(projectId)!.Documents.Single();
        var model = await document.GetSemanticModelAsync();
        var root = await document.GetSyntaxRootAsync();
        var secondImpl = (INamedTypeSymbol)model!.GetDeclaredSymbol(
            root!.DescendantNodes().First(n => n is Microsoft.CodeAnalysis.CSharp.Syntax.ClassDeclarationSyntax c && c.Identifier.Text == "SecondImpl"))!;
        var secondImplRuleIds = secondImpl.GetMembers("RuleIds").Single();

        // Act + assert: only FirstImpl's RuleIds is ever bound (via the contract),
        // yet the fellow implementation counts as referenced too.
        SolutionReferenceIndex.Get(solution).IsReferenced(secondImplRuleIds).Should().BeTrue();
    }

    [Fact]
    public async Task Treat_Dynamic_Dispatch_As_Evidence_For_IsReferenced()
    {
        // The FindReferencesAsync candidate-location doctrine: a name occurrence
        // that cannot be confirmed (here: a dynamic receiver) counts as evidence.
        using var workspace = new AdhocWorkspace();
        var (solution, projectId) = CreateSolution(
            ("UnderTest.cs", """
                namespace App;
                public sealed class UnderTest
                {
                    public void UpdateFirstName(string firstName) { }
                }
                """),
            ("Caller.cs", """
                namespace App;
                public static class Caller
                {
                    public static void Use(dynamic dyn) => dyn.UpdateFirstName("x");
                }
                """));

        var member = await GetNamedMemberAsync(solution, projectId, "UnderTest.cs", "UnderTest", "UpdateFirstName");

        SolutionReferenceIndex.Get(solution).IsReferenced(member).Should().BeTrue();
    }

    [Fact]
    public async Task Treat_Unbindable_Name_Occurrences_As_Evidence_For_IsReferenced()
    {
        // The broken-compilation shape: monorepo-scale workspaces inevitably
        // contain code that does not bind — FindReferencesAsync returned those
        // name matches as candidate locations, and they counted as references.
        using var workspace = new AdhocWorkspace();
        var (solution, projectId) = CreateSolution(
            ("UnderTest.cs", """
                namespace App;
                public sealed class UnderTest
                {
                    public void UpdateFirstName(string firstName) { }
                }
                """),
            ("Broken.cs", """
                namespace App;
                public static class BrokenCaller
                {
                    public static void Use() => Ghost.UpdateFirstName("x");
                }
                """));

        var member = await GetNamedMemberAsync(solution, projectId, "UnderTest.cs", "UnderTest", "UpdateFirstName");

        SolutionReferenceIndex.Get(solution).IsReferenced(member).Should().BeTrue();
    }

    [Fact]
    public async Task Not_Treat_Confirmed_Non_References_As_Evidence_For_IsReferenced()
    {
        // The doctrine's other side: a name whose every occurrence binds cleanly
        // to something ELSE is a confirmed non-reference — the member stays
        // unreferenced (old and new semantics agree).
        using var workspace = new AdhocWorkspace();
        var (solution, projectId) = CreateSolution(
            ("UnderTest.cs", """
                namespace App;
                public sealed class UnderTest
                {
                    public void UpdateFirstName(string firstName) { }
                }
                public sealed class Other
                {
                    public void UpdateFirstName(string firstName) { }
                }
                """),
            ("Caller.cs", """
                namespace App;
                public static class Caller
                {
                    public static void Use() => new Other().UpdateFirstName("x");
                }
                """));

        var member = await GetNamedMemberAsync(solution, projectId, "UnderTest.cs", "UnderTest", "UpdateFirstName");

        SolutionReferenceIndex.Get(solution).IsReferenced(member).Should().BeFalse();
    }

    private static (Solution Solution, ProjectId ProjectId) CreateSolution(params (string Name, string Source)[] documents)
    {
        var workspace = new AdhocWorkspace();
        var corlib = MetadataReference.CreateFromFile(typeof(object).Assembly.Location);
        var projectId = ProjectId.CreateNewId("App");

        var solution = workspace.CurrentSolution
            .AddProject(ProjectInfo.Create(projectId, VersionStamp.Create(), "App", "App", LanguageNames.CSharp,
                filePath: @"C:\repo\App\App.csproj"))
            .AddMetadataReference(projectId, corlib);

        foreach (var (name, source) in documents)
        {
            solution = solution.AddDocument(DocumentId.CreateNewId(projectId), name, SourceText.From(source),
                filePath: $@"C:\repo\App\{name}");
        }

        return (solution, projectId);
    }

    private static async Task<ISymbol> GetNamedMemberAsync(
        Solution solution,
        ProjectId projectId,
        string documentName,
        string typeName,
        string memberName)
    {
        var document = solution.GetProject(projectId)!.Documents.Single(d => d.Name == documentName);
        var model = await document.GetSemanticModelAsync();
        var root = await document.GetSyntaxRootAsync();
        var typeDeclaration = root!.DescendantNodes()
            .First(n => n is Microsoft.CodeAnalysis.CSharp.Syntax.ClassDeclarationSyntax c && c.Identifier.Text == typeName);
        var type = (INamedTypeSymbol)model!.GetDeclaredSymbol(typeDeclaration)!;
        return type.GetMembers(memberName).Single();
    }
}
