namespace Snipper.Tests;

using FluentAssertions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using Snipper.Analysis;
using Xunit;

public sealed class SymbolUsageCollectorShould
{
    [Fact]
    public async Task Include_Generated_And_External_Documents_As_Usage_Evidence_For_CollectUsedAssembliesAsync()
    {
        // Arrange: a library project plus a consumer that touches the library ONLY
        // from a generated file (obj\...) and a file linked from outside the
        // project directory. Both are usage evidence and must count.
        using var workspace = new AdhocWorkspace();
        var corlib = MetadataReference.CreateFromFile(typeof(object).Assembly.Location);

        var libId = ProjectId.CreateNewId("Lib");
        var consumerId = ProjectId.CreateNewId("Consumer");

        var solution = workspace.CurrentSolution
            .AddProject(ProjectInfo.Create(libId, VersionStamp.Create(), "Lib", "Lib", LanguageNames.CSharp,
                filePath: @"C:\repo\Lib\Lib.csproj"))
            .AddDocument(DocumentId.CreateNewId(libId), "LibType.cs", SourceText.From("namespace Lib; public sealed class LibType { }"),
                filePath: @"C:\repo\Lib\LibType.cs")
            .AddProject(ProjectInfo.Create(consumerId, VersionStamp.Create(), "Consumer", "Consumer", LanguageNames.CSharp,
                filePath: @"C:\repo\Consumer\Consumer.csproj"))
            .AddMetadataReference(consumerId, corlib)
            .AddProjectReference(consumerId, new ProjectReference(libId))
            .AddDocument(DocumentId.CreateNewId(consumerId), "Gen.cs", SourceText.From(
                "// <auto-generated/>\nnamespace Consumer; public sealed class GenUsage { public static Lib.LibType? Create() => null; }"),
                filePath: @"C:\repo\Consumer\obj\Gen.cs")
            .AddDocument(DocumentId.CreateNewId(consumerId), "External.cs", SourceText.From(
                "namespace Consumer; public sealed class ExternalUsage { public static Lib.LibType? Create() => null; }"),
                filePath: @"C:\elsewhere\External.cs");

        var consumer = solution.GetProject(consumerId)!;

        // Act
        var usedAssemblies = await SymbolUsageCollector.CollectUsedAssembliesAsync(consumer, CancellationToken.None);

        // Assert: the library assembly is used even though no non-skipped document references it.
        usedAssemblies.Should().Contain(a => a.Name == "Lib");
    }
}
