// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ProtoLike.proto
// </auto-generated>
#pragma warning disable 1591
namespace CoreLib;

public sealed class ProtoLikeMessage
{
    private int _protoUnusedField = 1;

    public int Read() => 0;
}
